name: MATLAB Test on GitHub Actions
on: [push, pull_request]
jobs:
  run-matlab-test:
    name: Execute MATLAB Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run Kagome_Test.m
        uses: matlab-actions/run-command@v1
        with:
          command: run('../CP2024-Group7/Kagome_Test.m')
